trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  resource_group_name: 'myTFResourceGroup'
  location: 'East US'

stages:
- stage: Terraform
  jobs:
  - job: DeployRG
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - script: |
        cat > terraform.tfvars <<EOF
        subscription_id     = "$(subscription_id)"
        client_id           = "$(client_id)"
        client_secret       = "$(client_secret)"
        tenant_id           = "$(tenant_id)"
        resource_group_name = "$(resource_group_name)"
        location            = "$(location)"
        EOF
      displayName: 'Generate terraform.tfvars'

    - script: terraform init
      displayName: 'Terraform Init'

    - script: terraform plan
      displayName: 'Terraform Plan'

    - script: terraform apply -auto-approve
      displayName: 'Terraform Apply'
