trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_VERSION: '1.6.0'

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '$(TF_VERSION)'

- script: |
    terraform init
  displayName: 'Terraform Init'

- script: |
    terraform plan -out=tfplan
  displayName: 'Terraform Plan'

- script: |
    terraform apply -auto-approve tfplan
  displayName: 'Terraform Apply'
