trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  resource_group_name: 'myTFResourceGroup'
  location: 'East US'

stages:
- stage: Terraform
  jobs:
  - job: DeployRG
    steps:

    # ✅ Step 1: Login to Azure using your Service Connection
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AZ-SPN-idmay25'  # <-- your service connection name
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Azure login successful"

    # ✅ Step 2: Install Terraform
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    # ✅ Step 3: Terraform Init (auth will now work)
    - script: terraform init
      displayName: 'Terraform Init'

    # ✅ Step 4: Terraform Plan
    - script: |
        terraform plan \
          -var="resource_group_name=$(resource_group_name)" \
          -var="location=$(location)"
      displayName: 'Terraform Plan'

    # ✅ Step 5: Terraform Apply
    - script: |
        terraform apply -auto-approve \
          -var="resource_group_name=$(resource_group_name)" \
          -var="location=$(location)"
      displayName: 'Terraform Apply'
