trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  resource_group_name: 'myTFResourceGroup'
  location: 'East US'

stages:
- stage: Terraform
  jobs:
  - job: DeployRG
    steps:

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    # Terraform Init
    - script: |
        set -e
        terraform init
      displayName: 'Terraform Init'

    # Terraform Plan
    - script: |
        set -e
        terraform plan \
          -var="subscription_id=$(subscription_id)" \
          -var="client_id=$(client_id)" \
          -var="client_secret=$(client_secret)" \
          -var="tenant_id=$(tenant_id)" \
          -var="resource_group_name=$(resource_group_name)" \
          -var="location=$(location)"
      displayName: 'Terraform Plan'

    # Terraform Apply
    - script: |
        set -e
        terraform apply -auto-approve \
          -var="subscription_id=$(subscription_id)" \
          -var="client_id=$(client_id)" \
          -var="client_secret=$(client_secret)" \
          -var="tenant_id=$(tenant_id)" \
          -var="resource_group_name=$(resource_group_name)" \
          -var="location=$(location)"
      displayName: 'Terraform Apply'
